services:
  app:
    image: pluto_container
    container_name: pluto_container
    working_dir: /app

    volumes:
      - ./:/app

    ports:
      - "8050:8050"

    stdin_open: true
    tty: true

    command: >
      bash -lc "
        pip3 install -e . &&
        python3 run_stream.py
      "
